# Generated by Django 3.2.7 on 2021-09-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('director', models.CharField(max_length=30)),
                ('actor', models.CharField(max_length=30)),
                ('poster', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
