cloud:
  aws:
    credentials:
      accessKey: AKIATS57JYAC73DVX5WX
      secretKey: 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
    s3:
      bucket: emotionplanet
    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB